# Generated by Django 3.0.7 on 2021-08-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210804_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_tille',
            new_name='car_title',
        ),
    ]
